Draft of etcd bootstrapping

diff --git a/templates/masters_etcd.yaml b/templates/masters_etcd.yaml
--- a/templates/masters_etcd.yaml
+++ b/templates/masters_etcd.yaml
@@ -106,7 +106,7 @@ Resources:
             #       VolumeSize: 30
             #       VolumeType: gp2
             UserData:
-                "Fn::Base64": !Sub |
+                "Fn::Base64": |
                     Content-Type: multipart/mixed; boundary="==BOUNDARY=="
                     MIME-Version: 1.0
 
@@ -133,8 +133,90 @@ Resources:
                     trap "cleanup" INT TERM EXIT
 
                     yum update -y
-                    yum install awscli
+                    yum install -y awscli
                     yum install -y docker
+
+                    DATA_DIR=/var/lib/etcd
+                    mkdir -p $DATA_DIR
+
+                    REGISTRY=quay.io/coreos/etcd
+                    ETCD_VERSION=v3.2
+
+                    INTERNAL_IP=$(curl -sS --retry 3 http://169.254.169.254/latest/meta-data/local-ipv4)
+                    EC2_INSTANCE_ID=$(curl -sS --retry 3 http://169.254.169.254/latest/meta-data/instance-id)
+                    HOSTNAME=$(curl -sS --retry 3 http://169.254.169.254/latest/meta-data/local-hostname)
+
+                    # Get ASG name the instance belong to
+                    ASG_NAME=$(aws autoscaling describe-auto-scaling-instances --instance-ids $EC2_INSTANCE_ID --query AutoScalingInstances[0].AutoScalingGroupName --out text)
+
+                    # Create query string to get all inService instances and desired state
+                    QUERY="AutoScalingGroups[?AutoScalingGroupName==\`$ASG_NAME\`].{size:DesiredCapacity,instances:Instances[?LifecycleState==\`InService\`].InstanceId}"
+                    DESIRED_SIZE=0
+                    ACTUAL_SIZE=0
+
+                    # Wait until ASG launch all instances with retry and back-off strategy
+                    for i in `seq 1 10`
+                    do
+                      # Query all inService instances and desired state and get desired number of instances
+                      ASG_DATA=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-name $ASG_NAME --query $QUERY  --output text)
+                      DESIRED_SIZE=$(echo "$ASG_DATA" | head -1)
+                      ACTUAL_SIZE=$(echo "$ASG_DATA" | grep -ci instance)
+                      # go out of cycle if the number of instances match the desired state
+                      [ $ACTUAL_SIZE -eq $DESIRED_SIZE ] && break
+                      # otherwise wait and try again
+                      echo "wait till all instances are InService"
+                      sleep $((i*3))
+                    done
+
+                    # Final test that ASG has been stabilized (because there are two exits from 'for' loop)
+                    [ $ACTUAL_SIZE -eq $DESIRED_SIZE ] || (echo "ASG hasn't stabilized"; exit 1)
+
+                    ETCD_INITIAL_CLUSTER=$(aws ec2 describe-instances --instance-ids $INSTANCES --query 'Reservations[].Instances[].[InstanceId,PrivateIpAddress]' --output text | sort | awk '{ printf("%s=https://%s:2380,", $1, $2) }' | sed 's/,$//g')
+
+                    cat > /etc/systemd/system/etcd.service <<EOF
+                    [Unit]
+                    Description=etcd
+                    After=docker.service
+                    Requires=docker.service
+                    Documentation=https://github.com/coreos
+
+                    [Service]
+                    TimeoutStartSec=0
+                    ExecStartPre=/usr/bin/docker pull ${REGISTRY}:${ETCD_VERSION}
+                    #ExecStartPre=/usr/bin/docker rm etcd
+                    ExecStart=docker run \\
+                      -p 2379:2379 \\
+                      -p 2380:2380 \\
+                      --net host \\
+                      --volume=${DATA_DIR}:/etcd-data \\
+                      --name etcd ${REGISTRY}:${ETCD_VERSION} \\
+                      /usr/local/bin/etcd \\
+                      --data-dir=/etcd-data --name ${EC2_INSTANCE_ID} \\
+                      --initial-advertise-peer-urls http://${INTERNAL_IP}:2380 \\
+                      --listen-peer-urls http://${INTERNAL_IP}:2380 \\
+                      --advertise-client-urls https://${INTERNAL_IP}:2379,http://127.0.0.1:2379 \\
+                      --listen-client-urls https://${INTERNAL_IP}:2379,http://127.0.0.1:2379 \\
+                      --initial-cluster ${ETCD_INITIAL_CLUSTER} \\
+                      --initial-cluster-state new --initial-cluster-token ${ASG_NAME}
+
+                    ExecStop=/usr/bin/docker stop etcd
+                    ExecStopPost=/usr/bin/docker rm -f etcd
+                    ExecReload=/usr/bin/docker restart etcd
+                    Restart=always
+                    RestartSec=10
+                    Type=notify
+                    NotifyAccess=all
+
+                    [Install]
+                    WantedBy=multi-user.target
+                    EOF
+
+
+                    sudo systemctl daemon-reload
+                    sudo systemctl enable docker
+                    sudo systemctl start docker
+                    sudo systemctl enable etcd
+                    sudo systemctl start etcd
                     --==BOUNDARY==
 
     AutoScalingGroup:
